const formations = [
  {
    icon: "✈️",
    title: "Flight Dispatcher",
    hours: "40–80 h",
    description: [
      "Planification & NOTAM",
      "Météo, perf & ETOPS",
      "Surveillance vol & OCC",
    ],
    linkMetier: "/metiers/dispatcher",
    inscription: "/inscription?formation=dispatcher",
    programme: "/formations/dispatcher",
  },
  {
    icon: "🧮",
    title: "Agent de Trafic",
    hours: "24–40 h",
    description: [
      "Loadsheet & masses",
      "Équilibrage & sécurité",
      "Optimisation opérationnelle",
    ],
    linkMetier: "/metiers/agent-trafic",
    inscription: "/inscription?formation=agent-trafic",
    programme: "/formations/loadsheets",
  },
  {
    icon: "🧍‍♂️",
    title: "Agent d’Escale",
    hours: "20–30 h",
    description: [
      "Accueil & procédures passagers",
      "Coordination sol / vol",
      "Gestion embarquement & ponctualité",
    ],
    linkMetier: "/metiers/agent-escale",
    inscription: "/inscription?formation=agent-escale",
    programme: "/formations/escale",
  },
  {
    icon: "🦺",
    title: "Superviseur de Piste",
    hours: "24–36 h",
    description: [
      "Sécurité & coordination piste",
      "Brief & supervision départ",
      "Interface OCC / équipes terrain",
    ],
    linkMetier: "/metiers/superviseur-piste",
    inscription: "/inscription?formation=superviseur-piste",
    programme: "/formations/piste",
  },
  {
    icon: "📡",
    title: "OCC Management",
    hours: "24–60 h",
    description: [
      "Process & tools",
      "Gestion aléas",
      "CBTA & reporting",
    ],
    linkMetier: "/metiers/coordinateur",
    inscription: "/inscription?formation=occ",
    programme: "/formations/occ",
  },
];
